title: Areeya Tipyasothi

theme: "hitchens-theme"
url: 'https://areeyat.github.io/'
baseurl: ''

atom_feed:
  hide: true

plugins:
  - jekyll-include-cache

collections:
  pad-thai:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "pad-thai"
    values:
      layout: splash
      show_date: false
  - scope:
      path: ""
      type: pages
    values:
      layout: splash